[package]
name = "isotest"
version = "0.1.0-dev.0"
description = "Enables a very specific unit testing pattern."
edition = "2021"
license = "MIT"
repository = "https://github.com/maackle/isotest-rust"

[dependencies]

[dev-dependencies]
assert-panic = "1"
derive_more = "0"
